
title: Goal Utility Company Limited
email: contect@goalutility.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ww3.goalutility.com" # the base hostname & protocol for your site
twitter_username: goalutility
github_username:  goalutility

brand: Goal Utility
slider: 1
feature: 


about: 
counter: 


service: 
our-team:
testimonia:
clients-brand:
latest-news:
subscribe:
contact:
    tex_id : 0105559127115
    email: contact@goalutility.com  ,  ratchakitim@gmail.com  , thanakorn@goalutility.com
    address: HQ  10/56  Soi changwatana 14 thungsonghong Laksi Bangkok 10210 (Thailand)
    tel   :  096-994-6526 

copyright:
  brand: Goal Utility Co., Ltd.
  url: http://goalutility.com


# Build settings
markdown: kramdown
analytics: 
google_verification:

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore,
    serve,
    .iml
]
