
title: Goal Utility Company Limited
email: contect@goalutility.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ww3.goalutility.com" # the base hostname & protocol for your site
twitter_username: goalutility
github_username:  goalutility

brand: Goal Utility
slider: 1
feature: 1


about: Our Company  was established from engineers with experience in their field and combination and become to us. We are team of experience in  Telecommunications Networks  , Enterprise networks  , Security System , Computer Systems , software  including  Equipment in Electrical-Electronics  and part that involve in business  more than that  we are sales , consults , provide , implements , services  in good quality and delivery  the system or project to our custormer on time.we have mission to succuss and we not stop learning new knowledge for improve our team to service to meet customer needs and satisfy.
counter: 1


service: d
our-team:
testimonia:
clients-brand:
latest-news:
subscribe:
contact:
    phone: +66 932 50 540
    emergency: 931 53 234
    email: contact@golautility.com
    address: Bangkok, Thailand, <br> Bangkok - Thailand

copyright:
  brand: Goal Utility Co., Ltd.
  url: http://goalutility.com


# Build settings
markdown: kramdown
analytics: 
google_verification:

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore,
    serve,
    .iml
]